### ISSUE TITLE
O(n^2) like memory required

### ISSUE THREAD

**Issue by jasonnicholson** [robb-brown/GFT#2]
This line of code takes O(n^2) memory. It should be rewritten to be more in line with the point of GFT to be O(n*log(n)). The consequences of  O(n^2) memory greatly reduce the usefulness of the GFT. Without an update, only small signals can be used.

https://github.com/robb-brown/GFT/blob/4c81e5c1aa206d8736c46705239341d4c0e8b212/gft.m#L24

**Comment by robb-brown** [comment]
Did I get the wrong operator? That line is supposed to do element-wise multiplication between SIG and windows. Each of those is a 1D array with length N, so the result should also be length N.

I just tried a 1 meg signal, which should have crushed my notebook if memory was O(N^2) and it worked fine, everything seems to check out.

Note that the interpolation function *is* N^2, but that it has an option for subsampling so that you can display a lower resolution spectrogram, or just the chunk you're interested in.

**Comment by jasonnicholson** [comment]
Well, it may not be a memory problem. I get what you are trying to do, I think. The error I see is below.

![image](https://user-images.githubusercontent.com/1058191/126185335-1aefbbc4-e05a-4be5-b59f-a6287ff22c5b.png)

`size(sig)` is [6104000 1]

`size(windows)` is [1 8388608]

`size(partitions)` is [1 46]

I'll look at this more closely in the evenings.

**Comment by robb-brown** [comment]
Ah, okay. It looks like if you .* a column vector with a row vector Matlab broadcasts each operand to be an NxM matrix, then multiplies them. Since the partitions and windows are constructed depending only on the size of sig, they end up always being row vectors. I'll add a check to make sure the windows are compatible with sig. Sorry, Matlab's inability to have 1 d arrays is a bit of a foreign concept to me.

In the meantime, you should be able to fix your problem by transposing sig before you transform it.

I'm also not sure what it will do if the length of sig is not a power of two, so you might have to pad it before transforming. There is definitely something weird going on there, because windows should be the same size as sig.

**Comment by jasonnicholson** [comment]
You were right. My mistake about transposing the signal. Thank you for the response. I have some questions and will email you. :)
